name: Env demo
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  folder: ./test
  S3_BUCKET_NAME: '.'

jobs:
  python_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.folder }}

      - name: Terraform Init
        run: terraform apply -auto-approve
        working-directory: ${{ env.folder }}

      - name: Debug
        run: terraform output aws_s3_bucket_name
      
      - name: Inject terraform outputs to ENV
        run: echo "S3_BUCKET_NAME=$(terraform output aws_s3_bucket_name | tr -d '"')" >> $GITHUB_ENV
        working-directory: ${{ env.folder }}

      - name: Setup python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Run python script
        run: python ${{ env.folder }}/test.py